[package]
name = "tui_template"
version = "0.1.0"
authors = ["Abebe123000 <takashi123000@yahoo.co.jp>"]
license = "MIT"
edition = "2021"

[dependencies]
crossterm = "0.26.1"
tui = { package = "ratatui", version = "0.21.0" , features = ["all-widgets"] }
